Use model-psp that us worker-order list
intergiro/merchant-client pull request #20
Opened 2022-02-09 11:25 UTC by Magnus93

- [ ] https://github.com/intergiro/model/pull/433

2022-02-10 10:31 UTC, marcushanses requested changes

2022-02-10 10:31 UTC, marcushanses commented on package.json
> +}
```suggestion
}

```

2022-02-10 10:31 UTC, marcushanses approved these changes

2022-02-15 08:20 UTC, nilssonemma approved these changes

2022-03-03 12:38 UTC, fredrikbryntesson approved these changes

2022-03-03 12:38 UTC, merged